# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-LAUTER-DEUTSCHER
version:      1.00
version_from: lib/Acme/LAUTER/DEUTSCHER.pm
installdirs:  site
requires:
    Lingua::Translate:             0.08
    PerlIO::via:                   0.02
    Test::More:                    0.54

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
